tailscale/github-action

- action.yml
Some self-hosted runners don't have $HOME set.
Fixes https://github.com/tailscale/github-action/issues/12
Signed-off-by: Denton Gentry <dgentry@tailscale.com>
> Don't rely on $HOME

- action.yml
In release 1.16 and later, "tailscale up" will block until it can
connect to tailscaled and bring the link up. There is not a need
to loop any more.
> Update to 1.18, remove loop

- action.yml
The current action doesn't allow for any customization of the `tailscale up` command.  The two current use cases we have for this are:
* advertising tags for granular ACLs
* setting --host-routes=false (the large number of config change propagations from the ephemeral machines was putting undue strain on network)
Additional this PR bumps the default version to 1.16.2
> Add optional `args` input to customize tailscale up command

- README.md
When I copy/pasted the code snippet GitHub Actions complained about an error in my YAML configuration. Seems like the indentation for the `with` key is off by one level.
> Fix code snippet indentation.

- action.yml
So tailscaled doesn't run with the authkey in its env. It doesn't need to know, so don't provide it. Defense in depth.
> Move 'tailscale up' to its own step.

- action.yml
This allows configuring the various aspects of tailscale that use environment variables (such as as the experiment flag required for OAuth authkeys, amongst others).
> preserve environment variables when calling sudo

- action.yml
This allows e.g. setting up `tailscaled` as a proxy. It is a simpler approach than https://github.com/tailscale/github-action/pull/46.
Signed-off-by: Dennis Schridde <dennis@metabase.com>
> Allow overriding tailscaled arguments

- action.yml
Verify the binary downloaded before unpacking or executing it, to enhance security. Opt-in by providing the `sha256sum` argument.
Signed-off-by: Dennis Schridde <dennis@metabase.com>
> Verify SHA256 checksum of downloaded file

- action.yml
Set a reasonable timeout to prevent jobs from hanging for hours (https://github.com/tailscale/github-action/issues/50). 5 minutes is way longer than should ever be necessary, but accounts for intermittent networking issues on either the actions runner or the Tailscale package or control server.  Users can always set a shorter timeout on their own action step.
Fixes #50
> add timeout on steps with network I/O

- .github/workflows/tailscale.yml
We periodically have reports of failures in the GitHub Action where there has been no recent change in Tailscale infrastructure and no indication of a problem in metrics or monitoring.
Right now we have to generate a pull request to get this test workflow to run. Allow it to be run manually whenever desired.
> workflow: allow manual testing

- README.md
Adds instructions to the README
- Defining Tailscale version
- Updating Tailscale as a dependancy using Renovate
> README.md: Add Tailscale version and dependency update

- .github/workflows/tailscale.yml
- README.md
- action.yml
If package or SHA download from pkgs.tailscale.com fails with a non-200 repsonse code, make the whole action fail. This catches things like incorrect versions.
Example failure: https://github.com/tailscale/github-action/actions/runs/8808942236/job/24178922442
Updates #118
> Fail if curl gets a non-200 response code

- README.md
- action.yml
Also, document usage of the action with Tailnet Lock.
Fixes #132
> action.yml: allow specifying a state directory

- .github/workflows/tailscale.yml
This makes sure that we test with the default version as specified in action.yml
Updates #cleanup
> .github/workflows: use default Tailscale version in CI

- action.yml
Fixes https://github.com/tailscale/github-action/issues/134
> Force timeout during connection

- README.md
> README: add note about required oauth scopes

- README.md
- action.yml
Allows setting the latest version to `latest` which will grab the latest version of tailscale. The default remains unchanged
Note: this updates the actual action script to find the latest version so we can validate the sha. 
Fixes #28
> Always pull latest version

- .github/workflows/tailscale.yml
- action.yml
Add support for running the action on windows-based GitHub runners.
Updates https://github.com/tailscale/github-action/issues/157
> {action.yml,.github}: add support for windows

- .github/workflows/tailscale.yml
- action.yml
Add support for running the action on macOS-based GitHub runners.
Updates https://github.com/tailscale/github-action/issues/157
> {action.yml,.github}: add support for macOS

- .github/workflows/tailscale.yml
Checking for hello is not the best way to verify that Tailscale is connected, and it recently broke because we stopped giving ephemeral nodes access to hello.
Instead, check for connection by parsing the status output as recommended in our KB article https://tailscale.com/kb/1073/hello
> CI: fix the connection check

- .github/workflows/tailscale.yml
Pin versions of GitHub actions that are used in our workflows.
Updates #cleanup
> .github/workflows: pin GitHub action versions

- action.yml
This PR adds caching for Tailscale binary downloads to improve workflow performance and reduce bandwidth usage.
Motivation
At our company, we've experienced occasional download failures when our GitHub Actions workflows run on slower network nodes. These intermittent failures disrupt our CI/CD pipelines and require manual intervention. By implementing caching, we can significantly reduce these failures and improve the reliability of our workflows.
Changes:
- Added SHA256-based cache keys for Linux and Windows platforms
- Separated checksum retrieval, caching, and download steps for better organization
- Optimized the download process to only fetch files when not available in cache
This change is backward compatible and requires no configuration changes from users.
related issues: #87 #156
> Cache tailscale binary file

- README.md
Document the `use-cache` input added in https://github.com/tailscale/github-action/pull/166
Updates: https://github.com/tailscale/github-action/issues/87
> README.md: document the `use-cache` input

- .github/workflows/tailscale.yml
- action.yml
Remove `.tgz` and `.msi` files after they have been downloaded. This was the behaviour of the action previous to `v3.2.0`, but our logic for caching removed the deletion of these files.
Can look at downloading these to temp folders to avoid the more complex logic here as a follow up, but this should unblock / fix the immediate regression.
Updates: https://github.com/tailscale/github-action/issues/170
> action.yml: properly remove temporary files after downloading

- .github/workflows/tailscale.yml
- README.md
- action.yml
This pull request adds the ability to use a federated OIDC workload identity from GitHub to authenticate a GitHub Action to the tailnet.
> {action.yml,.github}: add oidc workload identity federation flow to github action

- README.md
- action.yml
Every change to a Tailscale network causes the netmap - a map of which devices [can connect or know each other](https://tailscale.com/kb/1087/device-visibility) - to be recalculated and distributed to all nodes on the tailnet. When a node on the tailnet tries to connect to a peer, both devices must be allowed to connect according to their netmap. Computing and distributing updated netmap is an eventually consistent process, which means that when a node joins a tailnet there is a small delay before it can connect to the desired targets. If nodeA knows nodeB and tries to connect, but nodeB doesn't know nodeA yet, nodeA will experience what appears to it like a generic network error.
We have good reasons to believe this delay and generic error response is the cause of various issues and PRs …
> Added argument to test targets connectivity
